# Generated by Django 4.0.4 on 2022-05-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_area_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='image',
        ),
        migrations.CreateModel(
            name='All_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование картинки')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото полигона')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zones.area')),
            ],
        ),
    ]
