# Generated by Django 4.0.4 on 2022-05-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_alter_all_area_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_area',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Сылка на фото'),
            preserve_default=False,
        ),
    ]
