# Generated by Django 4.0.4 on 2022-05-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_all_area_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_area',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='zones.area'),
        ),
    ]
